//Types for Get Conversation
export const GET_SUPPORT_CONVERSATION_REQUEST =
  'GET_SUPPORT_CONVERSATION_REQUEST';
export const GET_SUPPORT_CONVERSATION_SUCCESS =
  'GET_SUPPORT_CONVERSATION_SUCCESS';
export const GET_SUPPORT_CONVERSATION_FAILURE =
  'GET_SUPPORT_CONVERSATION_FAILURE';

// Type for Create Conversation
export const CREATE_SUPPORT_CONVERSATION_REQUEST =
  'CREATE_SUPPORT_CONVERSATION-REQUEST';
export const CREATE_SUPPORT_CONVERSATION_SUCCESS =
  'CREATE_SUPPORT_CONVERSATION-SUCCESS';
export const CREATE_SUPPORT_CONVERSATION_FAILURE =
  'CREATE_SUPPORT_CONVERSATION-FAILURE';

//Type for Create Message
export const CREATE_SUPPORT_MESSAGE_REQUEST = 'CREATE_SUPPORT_MESSAGE_REQUEST';
export const CREATE_SUPPORT_MESSAGE_SUCCESS = 'CREATE_SUPPORT_MESSAGE_SUCCESS';
export const CREATE_SUPPORT_MESSAGE_FAILURE = 'CREATE_SUPPORT_MESSAGE_SUCCESS';
