export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
// user type

export const UPDATE_USER_TYPE_REQUEST = 'UPDATE_USER_TYPE_REQUEST';
export const UPDATE_SOCIAL_MEDIA_LINKS_REQUEST =
  'UPDATE_SOCIAL_MEDIA_LINKS_REQUEST';

export const UPDATE_PORTFOLIO_REQUEST = 'UPDATE_PORTFOLIO_REQUEST';
export const UPDATE_INTEREST_REQUEST = 'UPDATE_INTEREST_REQUEST';
export const UPDATE_TALENT_REQUEST = 'UPDATE_TALENT_REQUEST';
