//Types for ADDCARD
export const ADDCARD_REQUEST = 'ADDCARD_REQUEST';
export const ADDCARD_SUCCESS = 'ADDCARD_SUCCESS';
export const ADDCARD_FAILURE = 'ADDCARD_FAILURE';
//Types for GetCard
export const GET_PAYMENT_CARD_REQUEST = 'GET_PAYMENT_CARD_REQUEST';
export const GET_PAYMENT_CARD_SUCCESS = 'GET_PAYMENT_CARD_SUCCESS';
export const GET_PAYMENT_CARD_FAILURE = 'GET_PAYMENT_CARD_FAILURE';

//Types for deleteCard
export const DELETE_PAYMENT_CARD_REQUEST = 'DELETE_PAYMENT_CARD_REQUEST';
export const DELETE_PAYMENT_CARD_SUCCESS = 'DELETE_PAYMENT_CARD_SUCCESS';
export const DELETE_PAYMENT_CARD_FAILURE = 'DELETE_PAYMENT_CARD_FAILURE';

//Type for UpdateCard
export const UPDATE_PAYMENT_CARD_REQUEST = 'UPDATE_PAYMENT_CARD_REQUEST';
export const UPDATE_PAYMENT_CARD_SUCCESS = 'UPDATE_PAYMENT_CARD_SUCCESS';
export const UPDATE_PAYMENT_CARD_FAILURE = 'UPDATE_PAYMENT_CARD_FAILURE';

// ========== Add Bank Detail =======

export const ADD_BANK_REQUEST = 'ADD_BANK_REQUEST';
export const GET_BANK_LIST_REQUEST = 'GET_BANK_LIST_REQUEST';

export const DELETE_BANK_REQUEST = 'DELETE_BANK_REQUEST';

export const UPDATE_BANK_REQUEST = 'UPDATE_BANK_REQUEST';
