//Types for GetSupportTickets
export const GET_SUPPORT_TICKET_REQUEST = 'GET_SUPPORT_TICKET_REQUEST';
export const GET_SUPPORT_TICKET_SUCCESS = 'GET_SUPPORT_TICKET_SUCCESS';
export const GET_SUPPORT_TICKET_FAILURE = 'GET_SUPPORT_TICKET_FAILURE';

//Types for ADDCARD
export const Add_SUPPORT_TICKET_REQUEST = 'Add_SUPPORT_TICKET_REQUEST';
export const ADD_SUPPORT_TICKET_SUCCESS = 'ADD_SUPPORT_TICKET_SUCCESS';
export const ADD_SUPPORT_TICKET_FAILURE = 'ADD_SUPPORT_TICKET_FAILURE';
