require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13'
install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "1"

target 'Bestie' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  # use_flipper! 
  
  # use_flipper!({ 'Flipper' => '0.74.0' })
  # use_flipper!({ 'Flipper' => '0.174.0', })
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' }, configurations: ['Debug', 'Staging'])
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
  # use_flipper!({ 'Flipper-Folly' => '0.174.0' }, configurations: ['Debug', 'Staging'])



  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # :flipper_configuration => FlipperConfiguration.enabled(["Debug"], {"Flipper"=>"0.174.0"}),
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

  target 'BestieTests' do
    inherit! :complete
    # Pods for testing
  end

  # post_install do |installer|
  #   # flipper_post_install(installer)
  #   installer.pods_project.build_configurations.each do |config|
  #     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  #     installer.pods_project.build_configurations.each do |config|
  #       config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
  #       config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
  #     end
  #     installer.pods_project.targets.each do |target|
  #       target.build_configurations.each do |config|
  #         config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"
  #      end
  #   end
  # end


  
use_flipper!()
post_install do |installer|
  flipper_post_install(installer)
end
end
